_target_: rl4co.models.POMO

# During val/test only we apply dihedral transformations
num_augment: 8
loss_type: rl_loss
alpha: 1.0
pl_impl: stable
loss_kwargs: {}
free_loss_ir_json_path: null

metrics:
  train: ["loss", "reward", "po_loss", "pl_loss", "po_pref_rate"]
  val: ["reward", "max_reward", "max_aug_reward"]
  test: ${model.metrics.val}
  log_on_step: True
